from __future__ import annotations

import os
from pathlib import Path

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
DEFAULT_OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")
DEFAULT_GPT_MODEL = os.getenv("GPT_MODEL", "qwen2.5-coder:7b")  # change if your account uses a different id

GENERATED_PREFIX = "LLM_Generated"
GENERATED_PATTERN = f"{GENERATED_PREFIX}*Test"

DEFAULT_COVERAGE_THRESHOLD = 1
DEFAULT_COVERAGE_REFINEMENT_METRICS = ("line", "instruction", "branch")
DEFAULT_MAX_COVERAGE_REFINEMENTS = 5
DEFAULT_MAX_STAGNATION_ITERATIONS = 3

# Backward-compatible aliases used by existing pipeline code.
COVERAGE_THRESHOLD = DEFAULT_COVERAGE_THRESHOLD
COVERAGE_REFINEMENT_METRICS = DEFAULT_COVERAGE_REFINEMENT_METRICS
MAX_COVERAGE_REFINEMENTS = DEFAULT_MAX_COVERAGE_REFINEMENTS
MAX_STAGNATION_ITERATIONS = DEFAULT_MAX_STAGNATION_ITERATIONS

DEMO_OUT = Path("demo_out")

FALLBACK_JAVA_VERSION = "17"
DEFAULT_DOCKER_MAVEN_IMAGE = os.getenv("DOCKER_MAVEN_IMAGE")
DEFAULT_DOCKER_MAVEN_CACHE_VOLUME = os.getenv("DOCKER_MAVEN_CACHE_VOLUME", "llm-coverage-maven-cache")
